const DEFAULT_SERVER = 'https://tallycomm.com'

module.exports.getConfigFields = function () {
	return [
		{
			type: 'static-text',
			id: 'info',
			width: 12,
			label: 'TallyComm',
			value: 'Sends PGM/PVW tally to smartphone cameras via TallyComm. The room must match the one used by camera operators when they sign in.',
		},
		{
			type: 'textinput',
			id: 'server',
			label: 'Server URL',
			width: 8,
			default: DEFAULT_SERVER,
			tooltip: 'URL of the TallyComm server (use the default for the hosted service).',
		},
		{
			type: 'textinput',
			id: 'room',
			label: 'Room / Event code',
			width: 8,
			default: '',
			placeholder: 'e.g.: show-2026',
			tooltip: 'Exact room code. Must match the one used by camera operators.',
			required: true,
		},
		{
			type: 'textinput',
			id: 'apiKey',
			label: 'API Key',
			width: 12,
			default: '',
			placeholder: 'Leave empty if the server does not require it',
			tooltip:
				'Per-event API key generated by TallyComm when the producer activates the event in setup. The director can also retrieve or rotate it from the TEAM ACCESS panel.',
		},
	]
}
